### ISSUE TITLE
[hl] Compilation target not supported due to lackof Unicode RegEx support

### ISSUE THREAD

**Issue by grepsuzette** [mikestead/hx-yaml#20]
Hi I get this targeting HashLink on Haxe 4 RC 5
```
yaml/Parser.hx:2002: characters 9-81 : Compilation target not supported due to lackof Unicode RegEx support
```
Will HashLink be supported soon? (it would be a shame not to!)
Since this is likely the fault of HL API itself has there been an issue reported on github so I can follow the discussion?
(Or maybe there is some secret switch I can define so as to only support ASCII regex?)
Good job with this lib btw!

**Comment by emugel** [comment]
I made a miserable fork for HashLink without utf8 regex classes.
Your eyes will bleed so don't look at this and forgive me  https://github.com/emugel/hx-yaml/ 
I hope HashLink can quickly have what's missing here and I can go back to this one version.

**Comment by mikestead** [comment]
Hey @Gama11 thanks for your interested and fok.

I don't have a huge amount of time to maintain this library anymore. That said, if there was a solid PR which has support + test coverage, and which doesn't refactor or impact existing code then we may be able to get it released.

**Comment by cedx** [comment]
Same issue when targetting PHP 😢 

But PHP regular expressions supports Unicode since version 5.1.0:
https://www.php.net/manual/en/regexp.reference.unicode.php

The `EReg` class from the Haxe standard library uses these features (since v4.0.0, it seems it was not the case with v3.4.x):
https://github.com/HaxeFoundation/haxe/blob/4.1.2/std/php/_std/EReg.hx
